import type { AgentStateManifest } from '../types.js';

export const claudeManifest: AgentStateManifest = {
  id: 'claude',
  version: 4,
  aliases: ['claude-code'],
  rules: [
    {
      id: 'selected-approval',
      state: 'blocked',
      priority: 1200,
      region: { kind: 'numbered_prompt_card' },
      lineRegex: ['^\\s*(?:[│┃]\\s*)?[›❯>]\\s*1\\.\\s*(?:yes|allow|approve|proceed)\\b'],
      all: [{ any: [
        { regex: ['esc.{0,40}to.{0,40}cancel'] },
        { regex: ['tab.{0,40}to.{0,40}amend'] },
        { regex: ['press.{0,20}enter.{0,30}(?:confirm|continue|select)'] },
      ] }],
      visibleBlocker: true,
      automationSafe: true,
    },
    {
      id: 'title-busy-spinner',
      state: 'working',
      priority: 1100,
      region: { kind: 'osc_title' },
      regex: ['^[\\u2800-\\u28ff\\u25d0-\\u25d3]\\s'],
      visibleWorking: true,
    },
    {
      id: 'side-question-overlay',
      state: 'working',
      priority: 1020,
      region: { kind: 'bottom_non_empty_lines', count: 5 },
      lineRegex: ['^\\s*/btw(?:\\s|$)', 'esc to close\\s*$'],
      visibleWorking: true,
    },
    {
      id: 'transcript-viewer',
      state: 'unknown',
      priority: 1000,
      region: { kind: 'bottom_non_empty_lines', count: 5 },
      contains: ['showing detailed transcript'],
      all: [{ any: [
        { contains: ['ctrl+o', 'to toggle'] },
        { contains: ['ctrl+e', 'show all'] },
        { contains: ['ctrl+e', 'collapse'] },
        { contains: ['↑↓ scroll'] },
        { contains: ['? for shortcuts'] },
        { contains: ['ctrl+o', 'hide transcript'] },
      ] }],
      skipStateUpdate: true,
    },
    {
      id: 'interactive-form-controls',
      state: 'blocked',
      priority: 980,
      region: { kind: 'after_last_horizontal_rule' },
      contains: ['esc to cancel'],
      all: [{ any: [
        { contains: ['enter to confirm'] },
        {
          contains: ['enter to select'],
          all: [{ any: [
            { contains: ['tab/arrow keys to navigate'] },
            { contains: ['arrow keys to navigate'] },
            { contains: ['arrows to navigate'] },
            { contains: ['↑/↓ to navigate'] },
            { contains: ['↑↓ to navigate'] },
          ] }],
        },
      ] }],
      visibleBlocker: true,
    },
    {
      id: 'workflow-launch-question',
      state: 'blocked',
      priority: 975,
      region: { kind: 'whole_recent' },
      contains: ['run a dynamic workflow?', 'esc to cancel'],
      visibleBlocker: true,
    },
    {
      id: 'model-selection-overlay',
      state: 'unknown',
      priority: 965,
      region: { kind: 'whole_recent' },
      contains: ['select model', 'enter to set as default', 'esc to cancel'],
      not: [
        { contains: ['do you want to proceed?'] },
        { contains: ['enter to select'] },
      ],
      skipStateUpdate: true,
    },
    {
      id: 'ready-prompt-box',
      state: 'idle',
      priority: 950,
      region: { kind: 'prompt_box_body' },
      lineRegex: ['^\\s*[│┃]?\\s*❯(?:\\s|$)(?!\\s*\\d+\\.)'],
      not: [
        { contains: ['enter to select'] },
        { contains: ['esc to cancel'] },
        { contains: ['arrow keys to navigate'] },
        { contains: ['↑/↓ to navigate'] },
        { contains: ['↑↓ to navigate'] },
      ],
      visibleIdle: true,
    },
    {
      id: 'numbered-approval',
      state: 'blocked',
      priority: 900,
      region: { kind: 'bottom_lines', count: 18 },
      all: [
        { contains: ['do you want to proceed?'] },
        { any: [
          { contains: ['bash command'] },
          { contains: ['bash('] },
          { contains: ['tab to amend'] },
          { contains: ['ctrl+e to explain'] },
          { lineRegex: ['^\\s*(?:❯\\s*)?\\d+\\.\\s*(?:yes|no)\\b'] },
        ] },
      ],
      visibleBlocker: true,
    },
    {
      id: 'shell-yes-no-question',
      state: 'blocked',
      priority: 850,
      region: { kind: 'bottom_lines', count: 8 },
      lineRegex: ['\\((?:y/n|yes/no)\\)\\s*$'],
      visibleBlocker: true,
    },
    {
      id: 'visible-work-status',
      state: 'working',
      priority: 700,
      region: { kind: 'bottom_non_empty_lines', count: 6 },
      any: [
        { regex: ['esc.{0,24}to.{0,24}interrupt'] },
        { regex: ['\\(\\s*(?:\\d+m\\s*)?\\d+s\\s*[·•]'] },
        { regex: ['(?:working|thinking).{0,80}(?:context left|tokens?)'] },
      ],
      visibleWorking: true,
    },
    {
      id: 'title-ready',
      state: 'idle',
      priority: 250,
      region: { kind: 'osc_title' },
      regex: ['^✳\\s'],
      visibleIdle: true,
    },
    {
      id: 'progress-ready',
      state: 'idle',
      priority: 250,
      region: { kind: 'osc_progress' },
      regex: ['^4;0'],
      visibleIdle: true,
    },
  ],
};
